### ISSUE TITLE
Notifications Log

### ISSUE THREAD

**Issue by konradkeck** [antaresproject/logger#2]
## Requirements

1. Every notification should be logged into the database 
2. Admin should have a new Notifications Log section in the Logs menu
3. Information displayed on the view logs page:
   - Date (display full datetime)
   - Notification Name
   - Language
   - Title (e.g. email title)
   - Notification Type (email, sms, area notification etc)
   - User Level (Admin, Reseller, Client etc)
   - User (#id firstname lastname and link if view page for the admin level is available)
4. Filters:
   - Date Range (with time picker)
   - Notification Name
   - Language
   - User Level
5. Main filter: Notification type (default = All)
6. Actions:
   - Preview (main action on double click)
   - For area notification - make a notification for admin
   - For email/SMS - open popup with a preview
   - Delete
7. Mass actions: 
   - Delete
8. There should be an auto-remove option in the General Settings as this db table may grow very fast. I suggest “Remove notification logs every X days”.

## Mockup
@mountstone required?

**Comment by mountstone** [comment]
@konradkeck nope

**Comment by mountstone** [comment]
@konradkeck feature is available in 0.9.2 version
